DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(2000),
    img_path   VARCHAR(255),
    price      BIGINT,
    title      VARCHAR(255)
);

CREATE TABLE orders (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_sum BIGINT
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count      INT NOT NULL,
    product_id BIGINT
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count      INT NOT NULL,
    price      BIGINT,
    order_id   BIGINT,
    product_id BIGINT
);