spring.application.name=payment-service

server.port=8081

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

payment.initial-balance=100000

logging.level.ru.yandex.practicum.payment=INFO

# OAuth2
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL:http://localhost:8180}/realms/my-market/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.audiences=payment-service