spring.application.name=payment-service

server.port=8081

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

payment.initial-balance=100000

logging.level.ru.yandex.practicum.payment=INFO