logging.level.io.asyncer.r2dbc.mysql=DEBUG
logging.level.com.mysql=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.ru.yandex.practicum.mymarket=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive.result.method.annotation=DEBUG
