spring.application.name=my-market-app

spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

logging.level.com.mysql=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.ru.yandex.practicum.mymarket=DEBUG
