spring.application.name=my-market-app

spring.r2dbc.url=${R2DBC_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

cache.product-list.ttl-minutes=5

payment-service.url=${PAYMENT_SERVICE_URL:http://localhost:8081}


